version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
    networks:
      - backend
  admin:
    image: boogak/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    networks:
      - backend
  elastic:
    image: elasticsearch:2.3
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - backend
  elastic_init:
    build:
      dockerfile: .
      context: ../
    image: member-stats-sync
    container_name: member-stats-sync
    command:
      - /wait-for-it.sh
      - elastic:9200
      - --strict
      - --timeout=300
      - --
      - /es_init.sh
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./es_init.sh:/es_init.sh
    environment:
      ES_BASE_URI: http://elastic:9200
    networks:
      - backend

networks:
  backend: